# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de998527d3e9266931f480ed9f3e789fd13d0e00230187672ce4bccc427c6a8b1c944d386d38957aa3d554389252d6060268ecc65ccd4ea024c8fa4a11c0a658

test:
  secret_key_base: 8f21c45b2ea57f3339b2f77ccc3f53cb3bd30e6cbb13a0aae97ddd009cab99cbeed7f0a5c2c11f3869c8563923878cdd70f9b9a1c1a826f8b23f7b67dd146c66

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
